Added flatten function and changed the __repr__ function.
janaSunrise/HypeMaths pull request #9
Opened 2021-03-10 07:10 UTC by Rohith04MVK

Added flatten function and changed the __repr__ function to make the matrix look better.

2021-03-10 12:49 UTC, janaSunrise commented
The flake8 checks are behaving weird. Will it be fine If I use the changes and attribute your email i.e. `007rohitjj04@gmail.com` with the attribution and push it? 😁

2021-03-10 14:44 UTC, Rohith04MVK commented
And added a little bit of linting

2021-03-12 08:57 UTC, janaSunrise requested changes
One more thing is to keep the docstrings with gaps. It's for the doc generator to parse it and understand it easily. Hope you understand.

2021-03-12 08:57 UTC, janaSunrise commented on hypemaths/models/matrix.py
> +        '''
```suggestion
    def size(self) -> int:
        """
        Returns
        -------
        int
            The integer which is the total number of items in the matrix
        """
```
Use `"` double quotes for eveness

2021-03-12 08:57 UTC, janaSunrise commented on hypemaths/models/matrix.py
> +        '''
```suggestion
        """
        Return a flattened version of the matrix.
        All elements of the matrix are placed into a single row.
        Parameters
        ----------
        cls : {'list', 'tuple', 'Vector'}, Optional
            Type the flat matrix should be returned
        Returns
        -------
        list, tuple, Vector
            A tuple containing the dimensions of the matrix passed.

        Examples
        --------
        >>> m = hm.Matrix([[1,2], [3,4]])
        >>> m.flatten()
        list([[1, 2, 3, 4]])

        """
```
Same as above

2021-03-12 10:32 UTC, janaSunrise approved these changes
Good to go! 👍🏼

2021-03-12 10:33 UTC, merged